#!/usr/bin/env python3
"""G1 before install; verified scanner; pinned binary wheels; no model credentials."""
import hashlib
import io
import json
import os
import platform
import subprocess
import sys
import tarfile
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from security_harness.preflight import verify
from security_harness.dependencies import DependencyError, scan as dependency_scan
from security_harness.audit import AuditRun
from security_harness.results import digest_file, subject_digest, validate_policy, write_json


def install(audit):
    audit.stage("configuration")
    if sys.version_info[:2] != (3, 12):
        raise RuntimeError("use Python 3.12 for the pinned lock")
    policy = json.loads((ROOT / "security/policy.json").read_text())
    validate_policy(policy)
    audit.data["policy_digest"] = digest_file(ROOT / "security/policy.json")
    audit.data["subject_digest"] = subject_digest(ROOT)
    audit.stage("G1")
    packages = verify(ROOT / "requirements.lock", policy)
    try:
        sca = dependency_scan(ROOT / "requirements.lock")
    except DependencyError as exc:
        if exc.evidence:
            write_json(audit.output / "sbom.cdx.json", exc.evidence['sbom'])
            audit.add("G1", "ERROR", "scan", len(packages), len(exc.evidence['findings']),
                      "incomplete dependency query", packages=packages, sca=exc.evidence)
        raise
    write_json(audit.output / "sbom.cdx.json", sca["sbom"])
    audit.add("G1", "COMPLETED", "scan", len(packages), len(sca["findings"]),
              "installation provenance and OSV preflight", packages=packages, sca=sca)
    if sca["findings"]:
        raise RuntimeError("known dependency vulnerabilities; installation blocked")
    print(f"G1 preflight verified {len(packages)} pinned packages before installation", flush=True)
    audit.stage("scanner")
    scanner = json.loads((ROOT / "security/tools.lock.json").read_text())["gitleaks"]
    if platform.system() != "Linux" or platform.machine() not in ("x86_64", "AMD64"):
        raise RuntimeError("scanner pin currently supports Linux x86_64 only")
    binary = ROOT / ".tools/gitleaks"
    binary.parent.mkdir(exist_ok=True)
    if not binary.exists() or hashlib.sha256(binary.read_bytes()).hexdigest() != scanner["binary_sha256"]:
        with urllib.request.urlopen(scanner["url"], timeout=45) as response:
            body = response.read(32 * 1024 * 1024 + 1)
        if hashlib.sha256(body).hexdigest() != scanner["archive_sha256"]:
            raise RuntimeError("Gitleaks release checksum mismatch")
        with tarfile.open(fileobj=io.BytesIO(body), mode="r:gz") as archive:
            data = archive.extractfile("gitleaks").read()
        if hashlib.sha256(data).hexdigest() != scanner["binary_sha256"]:
            raise RuntimeError("Gitleaks executable checksum mismatch")
        binary.write_bytes(data)
        binary.chmod(0o755)
    from security_harness.secrets import scan
    audit.stage("G2")
    secret_scan = scan(ROOT, binary, ROOT / "security/gitleaks.toml", scanner["binary_sha256"])
    audit.add("G2", "COMPLETED", "scan", secret_scan["targets"], len(secret_scan["findings"]), "installation secret scan")
    if secret_scan["findings"]:
        raise RuntimeError("G2 found secrets; target dependency installation blocked")
    print(f"G2 scanned {secret_scan['targets']} files before installation", flush=True)
    audit.stage("installation")
    # This directory is owned/generated by bootstrap. Clear it so stale packages
    # or .pth files cannot survive a refresh of the approved lock.
    subprocess.run([sys.executable, "-m", "venv", "--clear", str(ROOT / ".venv")], check=True)
    python = str(ROOT / ".venv/bin/python")
    # Ignore package manager configuration and inherited index override variables.
    env = {k: v for k, v in os.environ.items() if not k.startswith(("PIP_", "UV_"))}
    env["PIP_CONFIG_FILE"] = os.devnull
    wheels = ROOT / ".state/wheels"
    wheels.mkdir(parents=True, exist_ok=True)
    base = [python, "-m", "pip", "--isolated", "--disable-pip-version-check", "--no-cache-dir"]
    subprocess.run(base + ["download", "--only-binary=:all:", "--no-deps", "--require-hashes",
                          "--index-url", "https://pypi.org/simple", "-r", str(ROOT / "requirements.lock"),
                          "--dest", str(wheels)], check=True, env=env)
    subprocess.run(base + ["install", "--no-index", "--find-links", str(wheels), "--only-binary=:all:",
                          "--no-deps", "--require-hashes", "-r", str(ROOT / "requirements.lock")], check=True, env=env)
    subprocess.run([python, "-m", "pip", "check"], check=True, env=env)
    print("Bootstrap complete; wheel-only environment and scanner verified")


def main():
    audit = AuditRun(ROOT, "bootstrap")
    try:
        install(audit)
        audit.data.update(decision="ALLOW", reasons=[])
    except (Exception, KeyboardInterrupt, SystemExit) as exc:
        audit.fail(exc)
    code = audit.finish((("G1", "scan"), ("G2", "scan")))
    print(f"Bootstrap {audit.data['decision']}: {audit.output / 'report.json'}")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
